"""End-to-end unit tests for argparse_usage generator."""

import argparse
import shutil
import subprocess
from pathlib import Path
from typing import Callable

import pytest

from argparse_usage import generate


def usage_available() -> bool:
    """Check if usage CLI is available."""
    return shutil.which("usage") is not None


def build_parser() -> argparse.ArgumentParser:
    """Build minimal parser that maintains coverage."""
    parent_parser = argparse.ArgumentParser(add_help=False)
    parent_parser.add_argument(
        "-v", "--verbose", action="store_true", help="Verbose output"
    )

    parser = argparse.ArgumentParser(
        prog="testcli",
        description="Minimal test CLI for coverage",
        parents=[parent_parser],
    )

    parser.add_argument("-f", "--force", action="store_true", help="Force operation")
    parser.add_argument("-c", "--count", action="count")
    parser.add_argument(
        "--test-args...", help="Test ellipsis in flag name", required=True
    )
    parser.add_argument("input", help="Input file")
    parser.add_argument("output", nargs="?", help="Output file")
    parser.add_argument("files", nargs="+", help="Input files")
    parser.add_argument("options", nargs=3, help="Options")

    subparsers = parser.add_subparsers(dest="command")
    subparsers.required = True

    status_cmd = subparsers.add_parser("status", help="Show status")
    status_cmd.add_argument("-a", "--all", action="store_true", help="Show all")
    status_cmd.add_argument("--tags", nargs="*", help="Tags to filter")

    config_cmd = subparsers.add_parser("config", help="Configuration")
    config_cmd.add_argument("key", help="Config key")
    config_cmd.add_argument("value", nargs="?", help="Config value")

    return parser


@pytest.mark.parametrize(
    "parser_builder,metadata,expected_kdl",
    [
        (
            build_parser,
            {"name": "testcli", "version": "1.0.0", "author": "Test Author"},
            """// @generated by argparse-usage from Python argparse

name "testcli"
bin "testcli"
version "1.0.0"
author "Test Author"
about "Minimal test CLI for coverage"

flag "-v --verbose" help="Verbose output" default=#false
flag "-f --force" help="Force operation" default=#false
flag "-c --count" default="0" count=#true
flag "--test-args..." {
  help "Test ellipsis in flag name"
  required #true
  arg <test-args>
}
arg "<input>" help="Input file"
arg "[output]" help="Output file" required=#false
arg "<files>..." help="Input files" var=#true var_min=1
arg "<options>..." help="Options" var=#true var_min=3 var_max=3
cmd status {
  help "Show status"
  flag "-a --all" help="Show all" default=#false
  flag "--tags" {
    help "Tags to filter"
    var #true
    var_min 0
    arg <tags>
  }
}
cmd config {
  help "Configuration"
  arg "<key>" help="Config key"
  arg "[value]" help="Config value" required=#false
}""",
        ),
    ],
)
def test_e2e_examples(
    parser_builder: Callable[[], argparse.ArgumentParser],
    metadata: dict,
    expected_kdl: str,
):
    """Test end-to-end integration with example parsers."""
    parser = parser_builder()
    spec = generate(parser, **metadata)

    assert spec == expected_kdl


@pytest.mark.skipif(not usage_available(), reason="usage CLI not installed")
@pytest.mark.parametrize(
    "parser_builder,metadata",
    [
        (
            build_parser,
            {"name": "testcli", "version": "1.0.0", "author": "Test Author"},
        ),
    ],
)
def test_usage_lint(
    tmp_path: Path,
    parser_builder: Callable[[], argparse.ArgumentParser],
    metadata: dict,
):
    """Test that generated specs are valid KDL using the usage CLI."""
    parser = parser_builder()
    spec = generate(parser, **metadata)

    fpath = tmp_path / "spec.kdl"
    fpath.write_text(spec)

    result = subprocess.run(
        ["usage", "lint", fpath.as_posix()],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
