"""Internal module to print Usage specs in KDL."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Spec:
    """Root usage spec node."""

    name: str | None = None
    bin: str | None = None
    version: str | None = None
    author: str | None = None
    about: str | None = None
    children: list = field(default_factory=list)

    def to_kdl(self) -> str:
        """Format a spec node to KDL."""
        printer = KDLPrinter()
        return printer.visit(self)


@dataclass
class Flag:
    """Flag/option node."""

    short: str | None = None
    long: str | None = None
    help: str | None = None
    required: bool = False
    default: Any = None
    count: bool = False
    var: bool = False
    var_min: int | None = None
    var_max: int | None = None
    choices: list[str] | None = None
    long_help: str | None = None
    takes_arg: bool = False


@dataclass
class Arg:
    """Positional argument node."""

    name: str
    help: str | None = None
    required: bool = True
    default: Any = None
    var: bool = False
    var_min: int | None = None
    var_max: int | None = None
    choices: list[str] | None = None
    long_help: str | None = None


@dataclass
class Cmd:
    """Command/subcommand node."""

    name: str
    help: str | None = None
    children: list = field(default_factory=list)


class Visitor(ABC):
    """Abstract visitor for AST traversal."""

    @abstractmethod
    def visit(self, node: Any) -> Any:
        """Visit a node and dispatch to appropriate visitor method."""
        pass

    @abstractmethod
    def visit_spec(self, node: Spec) -> Any:
        """Visit a Spec node."""
        pass

    @abstractmethod
    def visit_flag(self, node: Flag) -> Any:
        """Visit a Flag node."""
        pass

    @abstractmethod
    def visit_arg(self, node: Arg) -> Any:
        """Visit an Arg node."""
        pass

    @abstractmethod
    def visit_cmd(self, node: Cmd) -> Any:
        """Visit a Cmd node."""
        pass


class KDLPrinter(Visitor):
    """Visitor that prints AST as KDL."""

    def __init__(self) -> None:
        self.indent = "  "
        self._output: list[str] = []
        self._level = 0

    def visit(self, node: Any) -> str:
        """Visit a node and dispatch to appropriate visitor method."""
        if isinstance(node, Spec):
            return self.visit_spec(node)
        elif isinstance(node, Flag):
            self.visit_flag(node)
            return ""
        elif isinstance(node, Arg):
            self.visit_arg(node)
            return ""
        elif isinstance(node, Cmd):
            return self.visit_cmd(node)
        else:
            raise TypeError(f"Unknown node type: {type(node)}")

    def visit_spec(self, node: Spec) -> str:
        """Visit a Spec node and return KDL string."""
        self._output = ["// @generated by argparse-usage from Python argparse", ""]

        if node.name:
            self._output.append(f"name {self._escape(node.name)}")
        if node.bin:
            self._output.append(f"bin {self._escape(node.bin)}")
        if node.version:
            self._output.append(f"version {self._escape(node.version)}")
        if node.author:
            self._output.append(f"author {self._escape(node.author)}")
        if node.about:
            self._output.append(f"about {self._escape(node.about)}")

        self._output.append("")

        for child in node.children:
            self.visit(child)

        return "\n".join(self._output)

    def visit_flag(self, node: Flag) -> None:
        """Visit a Flag node."""
        if self._flag_needs_block(node):
            self._visit_flag_block(node)
        else:
            self._visit_flag_inline(node)

    def _visit_flag_inline(self, flag: Flag) -> None:
        """Visit flag inline (key=value syntax)."""
        flag_names = self._get_flag_names(flag)
        indent = self.indent * self._level
        parts = [f"{indent}flag {self._escape(flag_names)}"]

        if flag.help:
            parts.append(f"help={self._escape(flag.help)}")
        if flag.required:
            parts.append("required=#true")
        if flag.default is not None and flag.default != "==SUPPRESS==":
            parts.append(f"default={self._format_value(flag.default)}")
        if flag.count:
            parts.append("count=#true")
        if flag.var or flag.var_min is not None or flag.var_max is not None:
            parts.append("var=#true")
            if flag.var_min is not None:
                parts.append(f"var_min={flag.var_min}")
            if flag.var_max is not None:
                parts.append(f"var_max={flag.var_max}")

        self._output.append(" ".join(parts))

    def _visit_flag_block(self, flag: Flag) -> None:
        """Visit flag with block (key value syntax)."""
        flag_names = self._get_flag_names(flag)
        indent = self.indent * self._level
        lines = [f"{indent}flag {self._escape(flag_names)} {{"]

        if flag.help:
            lines.append(f"{indent}{self.indent}help {self._escape(flag.help)}")
        if flag.required:
            lines.append(f"{indent}{self.indent}required #true")
        if flag.default is not None and flag.default != "==SUPPRESS==":
            lines.append(
                f"{indent}{self.indent}default {self._format_value(flag.default)}"
            )
        if flag.count:
            lines.append(f"{indent}{self.indent}count #true")
        if flag.var or flag.var_min is not None or flag.var_max is not None:
            lines.append(f"{indent}{self.indent}var #true")
            if flag.var_min is not None:
                lines.append(f"{indent}{self.indent}var_min {flag.var_min}")
            if flag.var_max is not None:
                lines.append(f"{indent}{self.indent}var_max {flag.var_max}")
        if flag.long_help:
            lines.append(
                f"{indent}{self.indent}long_help={self._escape(flag.long_help)}"
            )

        if flag.choices:
            arg_name = flag.long.lstrip("-").rstrip("...") if flag.long else "value"
            lines.append(f"{indent}{self.indent}arg <{arg_name}> {{")
            lines.append(
                f"{indent}{self.indent}{self.indent}choices {' '.join(flag.choices)}"
            )
            lines.append(f"{indent}{self.indent}}}")
        elif flag.takes_arg:
            arg_name = flag.long.lstrip("-").rstrip("...") if flag.long else "value"
            lines.append(f"{indent}{self.indent}arg <{arg_name}>")

        lines.append(f"{indent}}}")
        self._output.extend(lines)

    def visit_arg(self, node: Arg) -> None:
        """Visit an Arg node."""
        if self._arg_needs_block(node):
            self._visit_arg_block(node)
        else:
            self._visit_arg_inline(node)

    def _visit_arg_inline(self, arg: Arg) -> None:
        """Visit arg inline (key=value syntax)."""
        arg_name = self._get_arg_name(arg)
        indent = self.indent * self._level
        parts = [f"{indent}arg {self._escape(arg_name)}"]

        if arg.help:
            parts.append(f"help={self._escape(arg.help)}")
        if not arg.required:
            parts.append("required=#false")
        if arg.default is not None and arg.default != "==SUPPRESS==":
            parts.append(f"default={self._escape(str(arg.default))}")
        if arg.var:
            parts.append("var=#true")
        if arg.var_min is not None:
            parts.append(f"var_min={arg.var_min}")
        if arg.var_max is not None:
            parts.append(f"var_max={arg.var_max}")

        self._output.append(" ".join(parts))

    def _visit_arg_block(self, arg: Arg) -> None:
        """Visit arg with block (key value syntax)."""
        arg_name = self._get_arg_name(arg)
        indent = self.indent * self._level
        lines = [f"{indent}arg {self._escape(arg_name)} {{"]

        if arg.help:
            lines.append(f"{indent}{self.indent}help {self._escape(arg.help)}")
        if not arg.required:
            lines.append(f"{indent}{self.indent}required #false")
        if arg.default is not None and arg.default != "==SUPPRESS==":
            lines.append(
                f"{indent}{self.indent}default {self._escape(str(arg.default))}"
            )
        if arg.var:
            lines.append(f"{indent}{self.indent}var #true")
        if arg.var_min is not None:
            lines.append(f"{indent}{self.indent}var_min {arg.var_min}")
        if arg.var_max is not None:
            lines.append(f"{indent}{self.indent}var_max {arg.var_max}")
        if arg.long_help:
            lines.append(
                f"{indent}{self.indent}long_help={self._escape(arg.long_help)}"
            )

        if arg.choices:
            lines.append(f"{indent}{self.indent}choices {' '.join(arg.choices)}")

        lines.append(f"{indent}}}")
        self._output.extend(lines)

    def visit_cmd(self, node: Cmd) -> str:
        """Visit a Cmd node."""
        indent = self.indent * self._level
        lines = [f"{indent}cmd {node.name} {{"]
        start_idx = len(self._output)
        self._output.extend(lines)

        if node.help:
            self._output.append(f"{indent}{self.indent}help {self._escape(node.help)}")

        self._level += 1
        for child in node.children:
            self.visit(child)
        self._level -= 1

        self._output.append(f"{indent}}}")
        return "\n".join(self._output[start_idx:])

    def _flag_needs_block(self, flag: Flag) -> bool:
        """Determine if flag needs block format."""
        return (
            flag.takes_arg
            or flag.choices is not None
            or (flag.long_help is not None and len(flag.long_help) > 50)
        )

    def _arg_needs_block(self, arg: Arg) -> bool:
        """Determine if arg needs block format."""
        return arg.choices is not None or (
            arg.long_help is not None and len(arg.long_help) > 50
        )

    def _get_flag_names(self, flag: Flag) -> str:
        """Get combined flag name string."""
        names = []
        if flag.short:
            names.append(flag.short)
        if flag.long:
            names.append(flag.long)
        return " ".join(names)

    def _get_arg_name(self, arg: Arg) -> str:
        """Get arg name with brackets."""
        if not arg.var and not arg.var_min and not arg.var_max:
            return f"[{arg.name}]" if not arg.required else f"<{arg.name}>"
        else:
            return f"[{arg.name}]..." if arg.var_min == 0 else f"<{arg.name}>..."

    def _format_value(self, value: Any) -> str:
        """Format a value (boolean, string, etc.)."""
        if isinstance(value, bool):
            return f"#{str(value).lower()}"
        else:
            return self._escape(str(value))

    def _escape(self, value: str) -> str:
        """Escape a string for KDL."""
        if not value:
            return '""'

        needs_raw = any(c in value for c in ['"', "\n", "\r", "\t", "\\"])
        if needs_raw:
            return f'r#"{value}"#'
        else:
            return f'"{value}"'
