"""Internal module to print Usage specs in KDL."""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Spec:
    """Root usage spec node."""

    name: str | None = None
    bin: str | None = None
    version: str | None = None
    author: str | None = None
    about: str | None = None
    children: list = field(default_factory=list)


@dataclass
class Flag:
    """Flag/option node."""

    short: str | None = None
    long: str | None = None
    help: str | None = None
    required: bool = False
    default: Any = None
    count: bool = False
    var: bool = False
    var_min: int | None = None
    var_max: int | None = None
    choices: list[str] | None = None
    long_help: str | None = None
    takes_arg: bool = False


@dataclass
class Arg:
    """Positional argument node."""

    name: str
    help: str | None = None
    required: bool = True
    default: Any = None
    var: bool = False
    var_min: int | None = None
    var_max: int | None = None
    choices: list[str] | None = None
    long_help: str | None = None


@dataclass
class Cmd:
    """Command/subcommand node."""

    name: str
    help: str | None = None
    children: list = field(default_factory=list)


class _KDLFormatter:
    """Formats usage spec AST to KDL."""

    def __init__(self) -> None:
        self.indent = "  "

    def format(self, node: Spec) -> str:
        """Format a spec node to KDL."""
        if not isinstance(node, Spec):
            raise TypeError(f"Expected Spec node, got {type(node)}")
        return self._format_spec(node)

    def _format_spec(self, spec: Spec) -> str:
        """Format root spec node."""
        lines = ["// @generated by argparse-usage from Python argparse", ""]

        if spec.name:
            lines.append(f"name {self._escape(spec.name)}")
        if spec.bin:
            lines.append(f"bin {self._escape(spec.bin)}")
        if spec.version:
            lines.append(f"version {self._escape(spec.version)}")
        if spec.author:
            lines.append(f"author {self._escape(spec.author)}")
        if spec.about:
            lines.append(f"about {self._escape(spec.about)}")

        lines.append("")

        for child in spec.children:
            if isinstance(child, Flag):
                lines.append(self._format_flag(child))
            elif isinstance(child, Arg):
                lines.append(self._format_arg(child))
            elif isinstance(child, Cmd):
                lines.append(self._format_cmd(child, level=0))

        return "\n".join(lines)

    def _format_flag(self, flag: Flag) -> str:
        """Format a flag node."""
        if self._flag_needs_block(flag):
            return self._format_flag_block(flag)
        else:
            return self._format_flag_inline(flag)

    def _format_flag_inline(self, flag: Flag) -> str:
        """Format flag inline (key=value syntax)."""
        flag_names = self._get_flag_names(flag)
        parts = [f"flag {self._escape(flag_names)}"]

        if flag.help:
            parts.append(f"help={self._escape(flag.help)}")
        if flag.required:
            parts.append("required=#true")
        if flag.default is not None and flag.default != "==SUPPRESS==":
            parts.append(f"default={self._format_value(flag.default)}")
        if flag.count:
            parts.append("count=#true")
        if flag.var or flag.var_min is not None or flag.var_max is not None:
            parts.append("var=#true")
            if flag.var_min is not None:
                parts.append(f"var_min={flag.var_min}")
            if flag.var_max is not None:
                parts.append(f"var_max={flag.var_max}")

        return " ".join(parts)

    def _format_flag_block(self, flag: Flag) -> str:
        """Format flag with block (key value syntax)."""
        flag_names = self._get_flag_names(flag)
        lines = [f"flag {self._escape(flag_names)} {{"]

        if flag.help:
            lines.append(f"  help {self._escape(flag.help)}")
        if flag.required:
            lines.append("  required #true")
        if flag.default is not None and flag.default != "==SUPPRESS==":
            lines.append(f"  default {self._format_value(flag.default)}")
        if flag.count:
            lines.append("  count #true")
        if flag.var or flag.var_min is not None or flag.var_max is not None:
            lines.append("  var #true")
            if flag.var_min is not None:
                lines.append(f"  var_min {flag.var_min}")
            if flag.var_max is not None:
                lines.append(f"  var_max {flag.var_max}")
        if flag.long_help:
            lines.append(f"  long_help={self._escape(flag.long_help)}")

        if flag.choices:
            arg_name = flag.long.lstrip("-").rstrip("...") if flag.long else "value"
            lines.append(f"  arg <{arg_name}> {{")
            lines.append(f"    choices {' '.join(flag.choices)}")
            lines.append("  }")
        elif flag.takes_arg:
            arg_name = flag.long.lstrip("-").rstrip("...") if flag.long else "value"
            lines.append(f"  arg <{arg_name}>")

        lines.append("}")
        return "\n".join(lines)

    def _format_arg(self, arg: Arg) -> str:
        """Format an arg node."""
        if self._arg_needs_block(arg):
            return self._format_arg_block(arg)
        else:
            return self._format_arg_inline(arg)

    def _format_arg_inline(self, arg: Arg) -> str:
        """Format arg inline (key=value syntax)."""
        arg_name = self._get_arg_name(arg)
        parts = [f"arg {self._escape(arg_name)}"]

        if arg.help:
            parts.append(f"help={self._escape(arg.help)}")
        if not arg.required:
            parts.append("required=#false")
        if arg.default is not None and arg.default != "==SUPPRESS==":
            parts.append(f"default={self._escape(str(arg.default))}")
        if arg.var:
            parts.append("var=#true")
        if arg.var_min is not None:
            parts.append(f"var_min={arg.var_min}")
        if arg.var_max is not None:
            parts.append(f"var_max={arg.var_max}")

        return " ".join(parts)

    def _format_arg_block(self, arg: Arg) -> str:
        """Format arg with block (key value syntax)."""
        arg_name = self._get_arg_name(arg)
        lines = [f"arg {self._escape(arg_name)} {{"]

        if arg.help:
            lines.append(f"  help {self._escape(arg.help)}")
        if not arg.required:
            lines.append("  required #false")
        if arg.default is not None and arg.default != "==SUPPRESS==":
            lines.append(f"  default {self._escape(str(arg.default))}")
        if arg.var:
            lines.append("  var #true")
        if arg.var_min is not None:
            lines.append(f"  var_min {arg.var_min}")
        if arg.var_max is not None:
            lines.append(f"  var_max {arg.var_max}")
        if arg.long_help:
            lines.append(f"  long_help={self._escape(arg.long_help)}")

        if arg.choices:
            lines.append(f"  choices {' '.join(arg.choices)}")

        lines.append("}")
        return "\n".join(lines)

    def _format_cmd(self, cmd: Cmd, level: int) -> str:
        """Format a command node."""
        indent = self.indent * level
        lines = [f"{indent}cmd {cmd.name} {{"]

        if cmd.help:
            lines.append(f"{indent}{self.indent}help {self._escape(cmd.help)}")

        for child in cmd.children:
            if isinstance(child, Flag):
                child_lines = self._format_flag(child).split("\n")
                for line in child_lines:
                    lines.append(f"{indent}{self.indent}{line}")
            elif isinstance(child, Arg):
                child_lines = self._format_arg(child).split("\n")
                for line in child_lines:
                    lines.append(f"{indent}{self.indent}{line}")
            elif isinstance(child, Cmd):
                child_lines = self._format_cmd(child, level + 1).split("\n")
                for line in child_lines:
                    lines.append(line)

        lines.append(f"{indent}}}")
        return "\n".join(lines)

    def _flag_needs_block(self, flag: Flag) -> bool:
        """Determine if flag needs block format."""
        return (
            flag.takes_arg
            or flag.choices is not None
            or (flag.long_help is not None and len(flag.long_help) > 50)
        )

    def _arg_needs_block(self, arg: Arg) -> bool:
        """Determine if arg needs block format."""
        return arg.choices is not None or (
            arg.long_help is not None and len(arg.long_help) > 50
        )

    def _get_flag_names(self, flag: Flag) -> str:
        """Get combined flag name string."""
        names = []
        if flag.short:
            names.append(flag.short)
        if flag.long:
            names.append(flag.long)
        return " ".join(names)

    def _get_arg_name(self, arg: Arg) -> str:
        """Get arg name with brackets."""
        if not arg.var and not arg.var_min and not arg.var_max:
            return f"[{arg.name}]" if not arg.required else f"<{arg.name}>"
        else:
            return f"[{arg.name}]..." if arg.var_min == 0 else f"<{arg.name}>..."

    def _format_value(self, value: Any) -> str:
        """Format a value (boolean, string, etc.)."""
        if isinstance(value, bool):
            return f"#{str(value).lower()}"
        else:
            return self._escape(str(value))

    def _escape(self, value: str) -> str:
        """Escape a string for KDL."""
        if not value:
            return '""'

        needs_raw = any(c in value for c in ['"', "\n", "\r", "\t", "\\"])
        if needs_raw:
            return f'r#"{value}"#'
        else:
            return f'"{value}"'
